DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS SampleAudioFile;
DROP TABLE IF EXISTS TrackedProgress;
DROP TABLE IF EXISTS BookRating;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS BannedAccount;
DROP TABLE IF EXISTS Account;
