<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>10a4af60-7901-4e67-add6-8c5caceb182f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-page']/div[3]/div[4]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Learn Flask I&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;Learn Flask I&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a0865a98-30ba-44e4-b6bf-cd05941bad1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/default-book-cover-dbdbf67e.png</value>
      <webElementGuid>677d255a-58dd-4503-ad55-24bca120cca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Learn Flask I</value>
      <webElementGuid>f415eadb-b3ee-4785-ba04-45ff09bb271c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-page&quot;)/div[@class=&quot;home-page-book-list&quot;]/div[@class=&quot;home-page-book-list-item&quot;]/div[@class=&quot;home-page-book-title&quot;]/div[@class=&quot;home-page-book-cover&quot;]/img[1]</value>
      <webElementGuid>71a3d209-73c7-4b43-8bdb-2e4551c80ed8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-page']/div[3]/div[4]/div/div/img</value>
      <webElementGuid>bc926f33-f807-4d9f-a316-37b5df4168cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Learn Flask I']</value>
      <webElementGuid>b786cd8c-d2a0-4b19-93a5-bb1b7d5a9c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/img</value>
      <webElementGuid>66c780c9-870f-492c-99db-556bb8a09116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/default-book-cover-dbdbf67e.png' and @alt = 'Learn Flask I']</value>
      <webElementGuid>4e403b4b-c1c1-4410-9508-f9ae1c2f284b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
