<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Page 1  2 of 3_read-book-page-navigation-icon</name>
   <tag></tag>
   <elementGuidId>f7f2c420-ce84-4ad5-80d9-7565596b114c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='read-book-page-navigation-section']/button[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Next&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b2c4a311-26d0-4231-b75f-7717d2d6f985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAABVSURBVHgB7ZTBCQAhDASXq+BKTQdn53sKKUBBFGUGQl5hJ3lEAjgF21Hr0y5SwLslChJIIIFEp0T0zjyai7O/Wk07fW5ftBrCCSf8/vAUiJEXC3AMP+yL3uUKpJmiAAAAAElFTkSuQmCC</value>
      <webElementGuid>83c59a6c-bf16-467b-b762-9b5f7389ce2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>729fd071-ce31-4718-9e0d-a2dbfc22cba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>read-book-page-navigation-icon</value>
      <webElementGuid>0145e2f1-b179-4ce9-b0c6-d575d199087b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;read-book-page-navigation-section&quot;)/button[@class=&quot;read-book-page-navigation-button&quot;]/img[@class=&quot;read-book-page-navigation-icon&quot;]</value>
      <webElementGuid>d17d0609-9e51-4345-8371-ff302f73c241</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='read-book-page-navigation-section']/button[2]/img</value>
      <webElementGuid>4029a9bd-c8e9-4d58-8a29-c11593cfbbf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Next']</value>
      <webElementGuid>2b7d9e19-e0cc-47ad-b830-cda116987500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>f159887e-d32f-4327-bab6-e3645a77c268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAABVSURBVHgB7ZTBCQAhDASXq+BKTQdn53sKKUBBFGUGQl5hJ3lEAjgF21Hr0y5SwLslChJIIIFEp0T0zjyai7O/Wk07fW5ftBrCCSf8/vAUiJEXC3AMP+yL3uUKpJmiAAAAAElFTkSuQmCC' and @alt = 'Next']</value>
      <webElementGuid>927237ea-184a-4d5f-bc6e-71251ac802fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
