<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to continue_landing-page-input-info_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18</name>
   <tag></tag>
   <elementGuidId>6158e0ee-fa40-4fa1-accd-7c7a1172dfb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='nguyenvanmuoi@gmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.landing-page-input-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c078e5ea-e7df-4c91-aca5-f90827aacacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>226719c3-8947-422c-9245-634a24b8c777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>181665cc-5d29-4740-af92-e7b73e1186d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landing-page-input-info</value>
      <webElementGuid>10776c4b-414f-4fbd-a3e3-3078381fc2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>nguyenvanmuoi@gmail</value>
      <webElementGuid>937160bd-f24b-4860-8d8a-317c5d3c0fd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landing-page-login-section&quot;)/form[1]/div[@class=&quot;landing-page-input-container&quot;]/input[@class=&quot;landing-page-input-info&quot;]</value>
      <webElementGuid>56826435-45ff-4602-831d-b42e1ee364c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='nguyenvanmuoi@gmail']</value>
      <webElementGuid>13689fc5-7465-43aa-9292-e627ec0d2c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landing-page-login-section']/form/div/input</value>
      <webElementGuid>7b55616c-7ecc-4970-880c-69240b0ae19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a58709aa-7302-4f97-831c-f4edb7148bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Enter your email']</value>
      <webElementGuid>722fc7bf-de56-4954-b6ad-09e6bae7f612</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
