<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to continue_landing-page-input-info_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>36111c3a-d65b-4fa5-b340-8b14c959434c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='nguyenv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.landing-page-input-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e967da7-411f-479c-af95-af1e1c704d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e6f2f9e8-620c-44e1-8b1c-fea46cda86cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>bb9ddcf9-d1a8-4134-87f5-d931e8146718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landing-page-input-info</value>
      <webElementGuid>267ad380-e704-44bf-8992-9a14d8d2a4b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>nguyenv</value>
      <webElementGuid>be37180f-6547-4d64-99ec-996aadd488fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landing-page-login-section&quot;)/form[1]/div[@class=&quot;landing-page-input-container&quot;]/input[@class=&quot;landing-page-input-info&quot;]</value>
      <webElementGuid>49c98433-d0a3-4095-809e-0fae1b070070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='nguyenv']</value>
      <webElementGuid>ced25257-c386-4059-b5dd-5f8b37a780e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landing-page-login-section']/form/div/input</value>
      <webElementGuid>ca081b83-0007-41b5-8daa-88aa555bbdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>abc961a8-e8d2-4631-be83-cf578fdf8985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Enter your email']</value>
      <webElementGuid>2181ab3c-c957-4c94-9a4d-ddc2166c0498</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
