<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Write a comment_star-icon</name>
   <tag></tag>
   <elementGuidId>fe39a5b3-e910-4a53-b503-676eac3eef02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='book-details-page-review-section']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.review-section-content > div.star-rating > img.star-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;1 Star&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8c193b4d-feff-439c-af4c-71ed337066ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAExSURBVHgB3VPLUcMwFNwnuGM6CB2YDpwLA5xIBSQdQAXQCUMF5MIQToEKoIOICvANLuSxkRWSONbnyGRnNLKfVvu+AnYC+oShPuMih7ufQ4LgEuq+xmlqAvqIEnt4a37QlzO8xPgGKRhcrdTTaUcjZO16ZMzWTDW+cCQD7jFBnaLAN70L9zlFDA5oLrh6XGXrxjsjXQha7h/eanl/vHDkmiJ91C4a4CZZBF1zsMxvjutl1Bsp+9G446UCORCK/GAk56vub9XQ122KJt0YLLMZyAlLsOGjA07UcFTCkdY8O+YIWWwFHYBO/CgHBOUUh10HJhBhhTiKEKe7p9IaFcUr133LVuYL6p93659bxTXk98jZGqcVcsH6zZjSrT50N8WdTfCZo+VejR/yOI+ckMP/jV+sWGHeBgKHrwAAAABJRU5ErkJggg==</value>
      <webElementGuid>bfa3bbdd-8f06-43ed-937b-b41b7ff0f890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>1 Star</value>
      <webElementGuid>61c01f07-8e8b-46d7-95f1-fe91a3ed3778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star-icon</value>
      <webElementGuid>1724fd79-7c62-40b9-84ac-77f69bb886a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book-details-page-review-section&quot;)/div[@class=&quot;review-section-content&quot;]/div[@class=&quot;star-rating&quot;]/img[@class=&quot;star-icon&quot;]</value>
      <webElementGuid>343c86b0-732e-4038-ad9b-4a21c2eda37d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='book-details-page-review-section']/div/div/img</value>
      <webElementGuid>a1042722-ef46-4215-b808-978a2de3ebf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='1 Star']</value>
      <webElementGuid>9bdb3f6c-fedc-4930-a793-7e965258be49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>02dea671-96a7-4d4a-ba0b-3b83bfc36517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAExSURBVHgB3VPLUcMwFNwnuGM6CB2YDpwLA5xIBSQdQAXQCUMF5MIQToEKoIOICvANLuSxkRWSONbnyGRnNLKfVvu+AnYC+oShPuMih7ufQ4LgEuq+xmlqAvqIEnt4a37QlzO8xPgGKRhcrdTTaUcjZO16ZMzWTDW+cCQD7jFBnaLAN70L9zlFDA5oLrh6XGXrxjsjXQha7h/eanl/vHDkmiJ91C4a4CZZBF1zsMxvjutl1Bsp+9G446UCORCK/GAk56vub9XQ122KJt0YLLMZyAlLsOGjA07UcFTCkdY8O+YIWWwFHYBO/CgHBOUUh10HJhBhhTiKEKe7p9IaFcUr133LVuYL6p93659bxTXk98jZGqcVcsH6zZjSrT50N8WdTfCZo+VejR/yOI+ckMP/jV+sWGHeBgKHrwAAAABJRU5ErkJggg==' and @alt = '1 Star']</value>
      <webElementGuid>42ba18ba-1a61-4aea-8382-473697f4db94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
