<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Write a comment_star-icon_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>2d1d4399-2b68-4f6b-9c47-b392fbd681b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='book-details-page-review-section']/div/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;2 Star&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>05ff96f0-76e5-45a3-a048-4782721b812b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAExSURBVHgB3VPLUcMwFNwnuGM6CB2YDpwLA5xIBSQdQAXQCUMF5MIQToEKoIOICvANLuSxkRWSONbnyGRnNLKfVvu+AnYC+oShPuMih7ufQ4LgEuq+xmlqAvqIEnt4a37QlzO8xPgGKRhcrdTTaUcjZO16ZMzWTDW+cCQD7jFBnaLAN70L9zlFDA5oLrh6XGXrxjsjXQha7h/eanl/vHDkmiJ91C4a4CZZBF1zsMxvjutl1Bsp+9G446UCORCK/GAk56vub9XQ122KJt0YLLMZyAlLsOGjA07UcFTCkdY8O+YIWWwFHYBO/CgHBOUUh10HJhBhhTiKEKe7p9IaFcUr133LVuYL6p93659bxTXk98jZGqcVcsH6zZjSrT50N8WdTfCZo+VejR/yOI+ckMP/jV+sWGHeBgKHrwAAAABJRU5ErkJggg==</value>
      <webElementGuid>961d3b17-9fbd-4091-8874-f30414875af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>2 Star</value>
      <webElementGuid>cc5a56b6-77bf-46ca-a7d9-e7e7f9255a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star-icon</value>
      <webElementGuid>182ddceb-3dff-43fa-9bbf-793602f1610b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book-details-page-review-section&quot;)/div[@class=&quot;review-section-content&quot;]/div[@class=&quot;star-rating&quot;]/img[@class=&quot;star-icon&quot;]</value>
      <webElementGuid>7bc801b4-6456-4e2b-aba4-c6232a4d8d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='book-details-page-review-section']/div/div/img[2]</value>
      <webElementGuid>d8fc6ec7-4f8e-40ac-89f1-24fe7183eb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='2 Star']</value>
      <webElementGuid>54fe16f5-4cd9-4edb-9eb6-2d862f5db75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img[2]</value>
      <webElementGuid>e9856776-eee0-43b9-ba6b-42cb6417e1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAExSURBVHgB3VPLUcMwFNwnuGM6CB2YDpwLA5xIBSQdQAXQCUMF5MIQToEKoIOICvANLuSxkRWSONbnyGRnNLKfVvu+AnYC+oShPuMih7ufQ4LgEuq+xmlqAvqIEnt4a37QlzO8xPgGKRhcrdTTaUcjZO16ZMzWTDW+cCQD7jFBnaLAN70L9zlFDA5oLrh6XGXrxjsjXQha7h/eanl/vHDkmiJ91C4a4CZZBF1zsMxvjutl1Bsp+9G446UCORCK/GAk56vub9XQ122KJt0YLLMZyAlLsOGjA07UcFTCkdY8O+YIWWwFHYBO/CgHBOUUh10HJhBhhTiKEKe7p9IaFcUr133LVuYL6p93659bxTXk98jZGqcVcsH6zZjSrT50N8WdTfCZo+VejR/yOI+ckMP/jV+sWGHeBgKHrwAAAABJRU5ErkJggg==' and @alt = '2 Star']</value>
      <webElementGuid>94df275e-a8ad-4d92-9339-cc5db92f574c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
