<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Write a comment_star-icon_1_2</name>
   <tag></tag>
   <elementGuidId>f6357b9f-0c6b-4011-879b-0e2fe1af4d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='book-details-page-review-section']/div/div/img[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;3 Star&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2282645d-ac87-4b59-b085-21974b5f971a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAExSURBVHgB3VPLUcMwFNwnuGM6CB2YDpwLA5xIBSQdQAXQCUMF5MIQToEKoIOICvANLuSxkRWSONbnyGRnNLKfVvu+AnYC+oShPuMih7ufQ4LgEuq+xmlqAvqIEnt4a37QlzO8xPgGKRhcrdTTaUcjZO16ZMzWTDW+cCQD7jFBnaLAN70L9zlFDA5oLrh6XGXrxjsjXQha7h/eanl/vHDkmiJ91C4a4CZZBF1zsMxvjutl1Bsp+9G446UCORCK/GAk56vub9XQ122KJt0YLLMZyAlLsOGjA07UcFTCkdY8O+YIWWwFHYBO/CgHBOUUh10HJhBhhTiKEKe7p9IaFcUr133LVuYL6p93659bxTXk98jZGqcVcsH6zZjSrT50N8WdTfCZo+VejR/yOI+ckMP/jV+sWGHeBgKHrwAAAABJRU5ErkJggg==</value>
      <webElementGuid>be539f46-f1b2-4da7-933f-ccc100fdfbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>3 Star</value>
      <webElementGuid>6c1fabd5-e66b-4699-a77f-c45268e43597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star-icon</value>
      <webElementGuid>e168fdf3-da7e-4146-80f1-dd175d000582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book-details-page-review-section&quot;)/div[@class=&quot;review-section-content&quot;]/div[@class=&quot;star-rating&quot;]/img[@class=&quot;star-icon&quot;]</value>
      <webElementGuid>f6b0d368-c12f-49bd-8362-13aca37668cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='book-details-page-review-section']/div/div/img[3]</value>
      <webElementGuid>c4a6b484-7821-4dfb-acb7-b5f6f66cd034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='3 Star']</value>
      <webElementGuid>781ff131-ed47-4a6a-8558-5debeec25f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img[3]</value>
      <webElementGuid>098d847e-5e6b-48d1-9eea-3cb631af944e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAExSURBVHgB3VPLUcMwFNwnuGM6CB2YDpwLA5xIBSQdQAXQCUMF5MIQToEKoIOICvANLuSxkRWSONbnyGRnNLKfVvu+AnYC+oShPuMih7ufQ4LgEuq+xmlqAvqIEnt4a37QlzO8xPgGKRhcrdTTaUcjZO16ZMzWTDW+cCQD7jFBnaLAN70L9zlFDA5oLrh6XGXrxjsjXQha7h/eanl/vHDkmiJ91C4a4CZZBF1zsMxvjutl1Bsp+9G446UCORCK/GAk56vub9XQ122KJt0YLLMZyAlLsOGjA07UcFTCkdY8O+YIWWwFHYBO/CgHBOUUh10HJhBhhTiKEKe7p9IaFcUr133LVuYL6p93659bxTXk98jZGqcVcsH6zZjSrT50N8WdTfCZo+VejR/yOI+ckMP/jV+sWGHeBgKHrwAAAABJRU5ErkJggg==' and @alt = '3 Star']</value>
      <webElementGuid>79b7d613-22a7-485b-b366-d4540498c355</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
