<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Write a comment_star-icon_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>b9ad3138-416f-4b99-90f6-3464c48a33ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='book-details-page-review-section']/div/div/img[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;5 Star&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>002440fe-cc75-4204-98e6-0a3e93bdeeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAUCAYAAABiS3YzAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHPSURBVHgBzVRLTgJBEK0au0eW3MDxBOINcGPUlSwNksAJgBMgJ1BOMPILS9gIiRvwBI4nYLjBbExggGmrYCYQGUKz0ko61V1d9frVJw3wl2Lb3aSur6HjZNsDS8pEFzRFC/TkBNKk0rpstUANAyqshTBLWv6HHJrN/j0pi/eIWNRhexCUgVgrFdTolJTyNH8wZpsRIlhKqSSicRaaLVppsr/6fqIs5WxM8B7ZXETlBYGa0N6j8rgA0slmrx0OEhGoEOgEATzTO9bmTTVRCr8Qg1qhcOW1Wv0qGamuRkopoMcjTtjz/e/eDlOWTmdgEfCQAggYXx4fb8oQI+sRgyFnQpnVcrm7Umz6m4Bh0jRnNjlzg0bz+TRTKGS86L7dfieWy+4aEKq53O3Tb4ydRnGa2exNhlKvcz2FSKS275VaMCuLduU4wFjQSKgJq9FZLKYOp9tovOXDq1Uz1s2Jl72ghmFcUCMc00wUpcRPOtut1mBMKbt8v1yq9L5YEWdkZrBuAh9TND4uMa/zzNJa/QE0dhdwDFMhVFhH9LgZvj+95A7TH3Ae1ppl718Qy5QDiOWHEJB/eLh1I2O4z7fbgxHpStjEEegIz6uO3zF/7P+UHxottiVMyb1NAAAAAElFTkSuQmCC</value>
      <webElementGuid>48aee1e6-5e4e-4d14-8ad1-3b4760d36445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>5 Star</value>
      <webElementGuid>7674cd0a-29ec-44e1-90c9-3916219c08cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star-icon</value>
      <webElementGuid>23e1acbe-b496-4a4c-881a-ca653b344ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book-details-page-review-section&quot;)/div[@class=&quot;review-section-content&quot;]/div[@class=&quot;star-rating&quot;]/img[@class=&quot;star-icon&quot;]</value>
      <webElementGuid>7df6d9e2-c2e9-4c67-898b-35e9cf4f60f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='book-details-page-review-section']/div/div/img[5]</value>
      <webElementGuid>2af08aad-edf6-4078-a6c3-2de08ac4ebac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='5 Star']</value>
      <webElementGuid>f36b22c0-a297-4a5f-a9ea-14264d224aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img[5]</value>
      <webElementGuid>b08ae883-89a6-4fea-961a-cfdc43b0c42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAUCAYAAABiS3YzAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHPSURBVHgBzVRLTgJBEK0au0eW3MDxBOINcGPUlSwNksAJgBMgJ1BOMPILS9gIiRvwBI4nYLjBbExggGmrYCYQGUKz0ko61V1d9frVJw3wl2Lb3aSur6HjZNsDS8pEFzRFC/TkBNKk0rpstUANAyqshTBLWv6HHJrN/j0pi/eIWNRhexCUgVgrFdTolJTyNH8wZpsRIlhKqSSicRaaLVppsr/6fqIs5WxM8B7ZXETlBYGa0N6j8rgA0slmrx0OEhGoEOgEATzTO9bmTTVRCr8Qg1qhcOW1Wv0qGamuRkopoMcjTtjz/e/eDlOWTmdgEfCQAggYXx4fb8oQI+sRgyFnQpnVcrm7Umz6m4Bh0jRnNjlzg0bz+TRTKGS86L7dfieWy+4aEKq53O3Tb4ydRnGa2exNhlKvcz2FSKS275VaMCuLduU4wFjQSKgJq9FZLKYOp9tovOXDq1Uz1s2Jl72ghmFcUCMc00wUpcRPOtut1mBMKbt8v1yq9L5YEWdkZrBuAh9TND4uMa/zzNJa/QE0dhdwDFMhVFhH9LgZvj+95A7TH3Ae1ppl718Qy5QDiOWHEJB/eLh1I2O4z7fbgxHpStjEEegIz6uO3zF/7P+UHxottiVMyb1NAAAAAElFTkSuQmCC' and @alt = '5 Star']</value>
      <webElementGuid>31a19648-3a08-47f6-8f70-956c2fdb3ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
