<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Write a comment_star-icon_1_2_3</name>
   <tag></tag>
   <elementGuidId>4614ed21-550b-4f9e-8367-e05d01e53cdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='book-details-page-review-section']/div/div/img[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;4 Star&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0a168e8-9cc0-4d53-951c-03eca6c3e831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAUCAYAAABiS3YzAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHPSURBVHgBzVRLTgJBEK0au0eW3MDxBOINcGPUlSwNksAJgBMgJ1BOMPILS9gIiRvwBI4nYLjBbExggGmrYCYQGUKz0ko61V1d9frVJw3wl2Lb3aSur6HjZNsDS8pEFzRFC/TkBNKk0rpstUANAyqshTBLWv6HHJrN/j0pi/eIWNRhexCUgVgrFdTolJTyNH8wZpsRIlhKqSSicRaaLVppsr/6fqIs5WxM8B7ZXETlBYGa0N6j8rgA0slmrx0OEhGoEOgEATzTO9bmTTVRCr8Qg1qhcOW1Wv0qGamuRkopoMcjTtjz/e/eDlOWTmdgEfCQAggYXx4fb8oQI+sRgyFnQpnVcrm7Umz6m4Bh0jRnNjlzg0bz+TRTKGS86L7dfieWy+4aEKq53O3Tb4ydRnGa2exNhlKvcz2FSKS275VaMCuLduU4wFjQSKgJq9FZLKYOp9tovOXDq1Uz1s2Jl72ghmFcUCMc00wUpcRPOtut1mBMKbt8v1yq9L5YEWdkZrBuAh9TND4uMa/zzNJa/QE0dhdwDFMhVFhH9LgZvj+95A7TH3Ae1ppl718Qy5QDiOWHEJB/eLh1I2O4z7fbgxHpStjEEegIz6uO3zF/7P+UHxottiVMyb1NAAAAAElFTkSuQmCC</value>
      <webElementGuid>0a02a56c-155f-4b0b-b3a8-2945122260f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>4 Star</value>
      <webElementGuid>33ef7a90-9962-4a17-8e4c-dd7f164dbb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star-icon</value>
      <webElementGuid>86a80348-e58d-4eb8-921a-787ccbf3af29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book-details-page-review-section&quot;)/div[@class=&quot;review-section-content&quot;]/div[@class=&quot;star-rating&quot;]/img[@class=&quot;star-icon&quot;]</value>
      <webElementGuid>7064b43c-4138-4e74-b3b4-a2e480bced25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='book-details-page-review-section']/div/div/img[4]</value>
      <webElementGuid>7a63ba9b-5d56-4789-a116-d3bd8d0c7785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='4 Star']</value>
      <webElementGuid>78bd5109-207c-4709-bf03-b9f6b68b261f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img[4]</value>
      <webElementGuid>f5334793-9523-4158-a26c-7c059a59bf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAUCAYAAABiS3YzAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHPSURBVHgBzVRLTgJBEK0au0eW3MDxBOINcGPUlSwNksAJgBMgJ1BOMPILS9gIiRvwBI4nYLjBbExggGmrYCYQGUKz0ko61V1d9frVJw3wl2Lb3aSur6HjZNsDS8pEFzRFC/TkBNKk0rpstUANAyqshTBLWv6HHJrN/j0pi/eIWNRhexCUgVgrFdTolJTyNH8wZpsRIlhKqSSicRaaLVppsr/6fqIs5WxM8B7ZXETlBYGa0N6j8rgA0slmrx0OEhGoEOgEATzTO9bmTTVRCr8Qg1qhcOW1Wv0qGamuRkopoMcjTtjz/e/eDlOWTmdgEfCQAggYXx4fb8oQI+sRgyFnQpnVcrm7Umz6m4Bh0jRnNjlzg0bz+TRTKGS86L7dfieWy+4aEKq53O3Tb4ydRnGa2exNhlKvcz2FSKS275VaMCuLduU4wFjQSKgJq9FZLKYOp9tovOXDq1Uz1s2Jl72ghmFcUCMc00wUpcRPOtut1mBMKbt8v1yq9L5YEWdkZrBuAh9TND4uMa/zzNJa/QE0dhdwDFMhVFhH9LgZvj+95A7TH3Ae1ppl718Qy5QDiOWHEJB/eLh1I2O4z7fbgxHpStjEEegIz6uO3zF/7P+UHxottiVMyb1NAAAAAElFTkSuQmCC' and @alt = '4 Star']</value>
      <webElementGuid>1f8bf5af-7721-41c5-b87d-97607a501c42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
