<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Write a comment_star-icon_1</name>
   <tag></tag>
   <elementGuidId>649c5439-2676-4491-b415-c99eaf59a7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='book-details-page-review-section']/div/div/img[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;3 Star&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>587e92a4-138d-4f5f-b574-410f8a4ae12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAUCAYAAABiS3YzAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHPSURBVHgBzVRLTgJBEK0au0eW3MDxBOINcGPUlSwNksAJgBMgJ1BOMPILS9gIiRvwBI4nYLjBbExggGmrYCYQGUKz0ko61V1d9frVJw3wl2Lb3aSur6HjZNsDS8pEFzRFC/TkBNKk0rpstUANAyqshTBLWv6HHJrN/j0pi/eIWNRhexCUgVgrFdTolJTyNH8wZpsRIlhKqSSicRaaLVppsr/6fqIs5WxM8B7ZXETlBYGa0N6j8rgA0slmrx0OEhGoEOgEATzTO9bmTTVRCr8Qg1qhcOW1Wv0qGamuRkopoMcjTtjz/e/eDlOWTmdgEfCQAggYXx4fb8oQI+sRgyFnQpnVcrm7Umz6m4Bh0jRnNjlzg0bz+TRTKGS86L7dfieWy+4aEKq53O3Tb4ydRnGa2exNhlKvcz2FSKS275VaMCuLduU4wFjQSKgJq9FZLKYOp9tovOXDq1Uz1s2Jl72ghmFcUCMc00wUpcRPOtut1mBMKbt8v1yq9L5YEWdkZrBuAh9TND4uMa/zzNJa/QE0dhdwDFMhVFhH9LgZvj+95A7TH3Ae1ppl718Qy5QDiOWHEJB/eLh1I2O4z7fbgxHpStjEEegIz6uO3zF/7P+UHxottiVMyb1NAAAAAElFTkSuQmCC</value>
      <webElementGuid>01a8d842-abe7-482f-9efa-578ef92c320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>3 Star</value>
      <webElementGuid>75d0537c-90f5-403b-9014-a54493e7264e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>star-icon</value>
      <webElementGuid>6be15441-d8bb-466b-9321-d1bc03c8b9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;book-details-page-review-section&quot;)/div[@class=&quot;review-section-content&quot;]/div[@class=&quot;star-rating&quot;]/img[@class=&quot;star-icon&quot;]</value>
      <webElementGuid>c76376d6-644c-4fde-93b5-e0b0999ecf94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='book-details-page-review-section']/div/div/img[3]</value>
      <webElementGuid>1cf1e671-ccf5-4982-9c33-974fd2bbbf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='3 Star']</value>
      <webElementGuid>4bea8747-86ca-4364-9c0c-dfb3ac6f13e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img[3]</value>
      <webElementGuid>8c8501d9-8362-4f5c-b0d4-71de4de823ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAUCAYAAABiS3YzAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAHPSURBVHgBzVRLTgJBEK0au0eW3MDxBOINcGPUlSwNksAJgBMgJ1BOMPILS9gIiRvwBI4nYLjBbExggGmrYCYQGUKz0ko61V1d9frVJw3wl2Lb3aSur6HjZNsDS8pEFzRFC/TkBNKk0rpstUANAyqshTBLWv6HHJrN/j0pi/eIWNRhexCUgVgrFdTolJTyNH8wZpsRIlhKqSSicRaaLVppsr/6fqIs5WxM8B7ZXETlBYGa0N6j8rgA0slmrx0OEhGoEOgEATzTO9bmTTVRCr8Qg1qhcOW1Wv0qGamuRkopoMcjTtjz/e/eDlOWTmdgEfCQAggYXx4fb8oQI+sRgyFnQpnVcrm7Umz6m4Bh0jRnNjlzg0bz+TRTKGS86L7dfieWy+4aEKq53O3Tb4ydRnGa2exNhlKvcz2FSKS275VaMCuLduU4wFjQSKgJq9FZLKYOp9tovOXDq1Uz1s2Jl72ghmFcUCMc00wUpcRPOtut1mBMKbt8v1yq9L5YEWdkZrBuAh9TND4uMa/zzNJa/QE0dhdwDFMhVFhH9LgZvj+95A7TH3Ae1ppl718Qy5QDiOWHEJB/eLh1I2O4z7fbgxHpStjEEegIz6uO3zF/7P+UHxottiVMyb1NAAAAAElFTkSuQmCC' and @alt = '3 Star']</value>
      <webElementGuid>d3807f90-4b70-46f9-9484-ddb5ee0c403b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
