<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I agree with the_agree-terms</name>
   <tag></tag>
   <elementGuidId>5855b209-ba14-47b6-8dad-b49a46b8edb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-page-agree-terms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register-page-agree-terms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#register-page-agree-terms</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d98b6081-53ee-4d3a-b4ba-ac3fcf421ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fc4c2794-41a2-4ca6-a833-6143821431a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-page-agree-terms</value>
      <webElementGuid>30c95014-4cec-43de-a9af-b5f9f5d6e113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>agree-terms</value>
      <webElementGuid>0d5a59bb-d1c1-4309-9706-a19b411e2716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-page-agree-terms&quot;)</value>
      <webElementGuid>31528876-a8d7-46bb-8164-63c85a4745d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register-page-agree-terms']</value>
      <webElementGuid>df1086c4-7e4a-4f55-ad49-169f5054e08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register-page-terms-container']/label/input</value>
      <webElementGuid>d858d42d-0019-49ea-9745-8aca9adb390f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>8f5ce816-2f96-40d4-8d87-fd6519845c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'register-page-agree-terms' and @name = 'agree-terms']</value>
      <webElementGuid>3f0e08b6-19d8-4cfa-8951-498ba95ae7cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
