<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up to continue_register-page-fir_7c751d</name>
   <tag></tag>
   <elementGuidId>525c55a8-52a0-43bf-b618-8552a60bf6dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-page-first-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register-page-first-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Create password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d064510-bb3d-4a91-8fbf-80b2638b9592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-page-first-password-input</value>
      <webElementGuid>d6ceacce-21ce-4370-843b-3b11bd5a7e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ed8b6960-9330-4e82-81de-645be84307bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Create password</value>
      <webElementGuid>85a15fa3-ff8a-41c8-a8e1-a54775bc821d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-page-input-info</value>
      <webElementGuid>865f9809-86e2-4b5e-b8f1-1a0c6a01d944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>76635bc6-da5f-433d-947c-f86bb5fc8b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-page-first-password-input&quot;)</value>
      <webElementGuid>c073ac44-8c0a-4a3f-a342-6beffca42b31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register-page-first-password-input']</value>
      <webElementGuid>524f1631-c45a-4434-a64b-e32cb673714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register-page-signup-section']/form/div[3]/input</value>
      <webElementGuid>1276e0c3-da91-496d-b453-6b0e69959b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>1a8bef7c-78b2-4350-a371-0dc6b8aa80fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register-page-first-password-input' and @type = 'password' and @placeholder = 'Create password']</value>
      <webElementGuid>6ce201a0-b2e7-4f99-a47f-99c4b35a672c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
