<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign up to continue_register-page-sec_cbf5a7</name>
   <tag></tag>
   <elementGuidId>e36d47f9-2c70-43ba-8943-14cbeb02f4cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-page-second-password-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register-page-second-password-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Confirm password&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adc1784e-33c8-4374-bd52-7c0a83c6ba47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-page-second-password-input</value>
      <webElementGuid>c8ddaeb3-29b2-43ca-aad2-5d5569fa098e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bc5f60c7-dd45-439d-9858-36c66ba14b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Confirm password</value>
      <webElementGuid>1299084e-e46a-44d5-b5ee-f61c00c52abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-page-input-info</value>
      <webElementGuid>07323ef3-e1e8-4263-a125-238404b1f01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-page-second-password-input&quot;)</value>
      <webElementGuid>1448eefa-2873-4de3-9a58-280c7e4bb1f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register-page-second-password-input']</value>
      <webElementGuid>8586251e-ce80-4f22-9e15-eae3927a57c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register-page-signup-section']/form/div[4]/input</value>
      <webElementGuid>227131a4-9629-4ee5-9dc0-6061e2425bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>46faea9b-b0f9-4f12-88f4-2748fb13b05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register-page-second-password-input' and @type = 'password' and @placeholder = 'Confirm password']</value>
      <webElementGuid>3352804b-471f-4afd-b5a1-d9c2d42daea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
