<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_d</name>
   <tag></tag>
   <elementGuidId>6c935bcd-f06a-4f02-88ea-8d0f083fb2da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.register-page-input-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='register-page-signup-section']/form/div[6]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Write your bio here&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3f701179-2062-4e27-8a90-154f7a81fea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write your bio here</value>
      <webElementGuid>df0a11fc-f699-44d0-b5ae-2d50fb883561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register-page-input-info</value>
      <webElementGuid>446f7623-a51e-4ecb-bed3-0f5cb8436bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>7deb9f06-ab1b-4da7-9ae0-2e980b34b759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>d</value>
      <webElementGuid>9090fa56-77ee-45f8-8a93-ebcbbfe5c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-page-signup-section&quot;)/form[1]/div[@class=&quot;register-page-input-container&quot;]/textarea[@class=&quot;register-page-input-info&quot;]</value>
      <webElementGuid>e3f9f31c-66a5-4530-a1ce-e3673312257e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='register-page-signup-section']/form/div[6]/textarea</value>
      <webElementGuid>f06c9308-88b9-445e-b738-372e5ab662c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up to continue'])[1]/following::textarea[1]</value>
      <webElementGuid>a8a7b942-ef84-471e-bc68-02d688990e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to PageRhythm'])[1]/following::textarea[1]</value>
      <webElementGuid>4e98c14a-088b-4dfd-8e94-95cd31f18422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms and Conditions'])[1]/preceding::textarea[1]</value>
      <webElementGuid>5f52b626-ea2c-4284-ac8d-29d4a7341f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='d']/parent::*</value>
      <webElementGuid>831ed3bc-7d0e-422d-91a5-c089627cdf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1b5802a1-3ddc-4723-92e1-80dc1fd3a0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Write your bio here' and (text() = 'd' or . = 'd')]</value>
      <webElementGuid>311e776c-e13c-48c7-89b6-0bdd7870036e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
