<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to continue_landing-page-input-info_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20</name>
   <tag></tag>
   <elementGuidId>2008cea1-e3ec-4257-9756-86996636ed30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.landing-page-input-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='nguyenvanmuoi@gmail.c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99cf5556-726b-4aab-9f83-11f7a6b8120e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7bf1121a-9704-4b64-851f-e1255c4a216c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>3b75cfbb-4a42-4446-8da9-1b650d670a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landing-page-input-info</value>
      <webElementGuid>d6b8a673-9ee4-4853-97e3-29c45e4073e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>nguyenvanmuoi@gmail.c</value>
      <webElementGuid>0c3f5c62-8b60-4af3-964a-cc1915a2bb89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landing-page-login-section&quot;)/form[1]/div[@class=&quot;landing-page-input-container&quot;]/input[@class=&quot;landing-page-input-info&quot;]</value>
      <webElementGuid>68576fa7-bfbe-49d4-849b-f02ea3e6e5e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='nguyenvanmuoi@gmail.c']</value>
      <webElementGuid>04c2c123-157c-4bda-8ce7-c943ddbbd914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landing-page-login-section']/form/div/input</value>
      <webElementGuid>cf9f7ef9-767a-41eb-9a05-16991d051abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3f962c1b-97e6-4d11-8d1a-8a7a371ac19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Enter your email']</value>
      <webElementGuid>60e07221-247a-41f2-96fa-24c19fe36094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
