<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login to continue_landing-page-input-info_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>a7352d8e-5289-4081-bb8b-2c846e05e365</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.landing-page-input-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='nguyenv']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e34f59d-3424-41e3-9714-826103a584c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>45cc4910-6deb-4ebd-81e5-07e9a9b0a054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>ac2e8849-367f-4526-b5fe-995e867e9023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>landing-page-input-info</value>
      <webElementGuid>db894c1b-e693-46e3-b72a-bd8185995a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>nguyenv</value>
      <webElementGuid>634a304c-a06e-48df-814a-d00ca4e92c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landing-page-login-section&quot;)/form[1]/div[@class=&quot;landing-page-input-container&quot;]/input[@class=&quot;landing-page-input-info&quot;]</value>
      <webElementGuid>a9ea98c7-1669-4eab-8024-8ecf324ff54b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='nguyenv']</value>
      <webElementGuid>455660c1-e7de-4526-9b21-aa601fae8986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landing-page-login-section']/form/div/input</value>
      <webElementGuid>07df5e7b-fee9-4d92-a031-d10844e72c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8c5a03aa-7fa0-43b9-b702-a64539d871f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Enter your email']</value>
      <webElementGuid>ca269d6e-6203-4dd1-b425-f9fc0909b882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
