<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Whats a g</name>
   <tag></tag>
   <elementGuidId>2da16a91-0d22-47cd-968d-c86626dfc529</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='comment-textarea']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter your comment...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fc281308-6663-4679-b2cb-82d7e0050fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment-textarea</value>
      <webElementGuid>cfcdb4f5-e447-406d-811d-5194433553ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your comment...</value>
      <webElementGuid>daa980fe-d58c-4ca2-8c8f-8bc9e1dddae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What's a g</value>
      <webElementGuid>3f884ee4-ccb4-429f-8d24-afa6a71b2219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment-textarea&quot;)</value>
      <webElementGuid>6acb8d9b-6304-4b31-8ec6-b57d7d1d4200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='comment-textarea']</value>
      <webElementGuid>08a037a4-e8f4-495e-a9ee-4f7201440f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='book-details-page']/div[5]/div/textarea</value>
      <webElementGuid>f55cd6f8-9348-492d-98c0-0fbfd2206252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write your comment here'])[1]/following::textarea[1]</value>
      <webElementGuid>7d94a9c0-31e6-4367-a015-6ac95e2cce5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply comment'])[16]/following::textarea[1]</value>
      <webElementGuid>22449fa0-6837-40e6-b4fb-aeaaadb40bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ffc21bd0-eee2-47f9-bd28-a4f3ae9c9d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>8b3a9ccd-6d87-43a1-9851-99c7e8921e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'comment-textarea' and @placeholder = 'Enter your comment...' and (text() = concat(&quot;What&quot; , &quot;'&quot; , &quot;s a g&quot;) or . = concat(&quot;What&quot; , &quot;'&quot; , &quot;s a g&quot;))]</value>
      <webElementGuid>e27edfa5-9349-4cdc-a032-59a2b22b559e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
